---
- name: atualizar cache
  apt:
    update_cache: yes

- name: atualizando todos os pacotes instalados
  apt:
    name: "*"
    state: latest

- name: instalando pacotes essenciais
  apt:
    name:
      - vim
      - bash-completion
      - htop
      - wget
      - curl

- name: removendo vim-tiny
  apt:
    name: vim-tiny
    state: absent

- name: adicionar usuario
  user:
    name: locio
    shell: /bin/bash
    create_home: true

- name: adicionado usuario ao sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "locio  ALL=(All) NOPASSWD: ALL"

- name: modificar /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: "^(#)?{{item.key}}"
    line: "{{item.key}} {{item.value}}"
    state: present
  loop:
    - { key: "Port", value: "2222"}
    - { key: "PermitionRootLogin", value: "no"}
    - { key: "PasswordAuthtentication", value: "no"}
    - { key: "AllowUsers", value: "locio"}
  notify:
    - systemctl restart sshd