---
- name: Pré-instalação do Docker
  apt:
    name:
      - ca-certificates
      - curl
    update_cache: yes

- name: Adicionar chave GPG ao repositório
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg  

- name: Adicionar repo Docker ao sources
  apt_repository: 
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Instalação do Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: yes

- name: Adicionando grupo docker
  group:
    name: docker
    state: present
    
- name: Adicionando usuário ao grupo docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Ativar e iniciar os serviços docker
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker.service
    - containerd.service